services:
  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_DB: bingo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:${POSTGRES_PORT:?POSTGRES_PORT required}:5432"
    volumes:
      - bingo-postgres-data:/var/lib/postgresql

  redis:
    image: redis:8.6
    ports:
      - "127.0.0.1:${REDIS_PORT:?REDIS_PORT required}:6379"

volumes:
  bingo-postgres-data:
